/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appgame_56132583;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Timer;

public class Main_game extends javax.swing.JFrame {

    public int a, b, kq, tg, moctg, diem, kt, max, dokho = 99;
    public Timer time;
    boolean ketthuc;
    public Main_game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Progress = new javax.swing.JProgressBar();
        lbcauhoi = new javax.swing.JLabel();
        btchoi = new javax.swing.JButton();
        btthoat = new javax.swing.JButton();
        lbasd = new javax.swing.JLabel();
        lbdiem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbkyluc = new javax.swing.JLabel();
        lbdokho = new javax.swing.JLabel();
        btsai = new javax.swing.JButton();
        btdokho1 = new javax.swing.JButton();
        btdokho2 = new javax.swing.JButton();
        btdokho3 = new javax.swing.JButton();
        btdung = new javax.swing.JButton();
        btcuu = new javax.swing.JButton();
        bthoisinh = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("TRÒ CHƠI PHÉP TOÁN TỐC ĐỘ");

        lbcauhoi.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbcauhoi.setText("Câu hỏi");

        btchoi.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        btchoi.setText("BẮT ĐẦU");
        btchoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btchoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchoiActionPerformed(evt);
            }
        });

        btthoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btthoat.setText("THOÁT");
        btthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthoatActionPerformed(evt);
            }
        });

        lbasd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbasd.setText("ĐIỂM:");

        lbdiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbdiem.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Kỷ lục:");

        lbkyluc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbkyluc.setText("0");

        lbdokho.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lbdokho.setText("Độ khó:");

        btsai.setBackground(new java.awt.Color(204, 255, 255));
        btsai.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        btsai.setForeground(new java.awt.Color(255, 0, 0));
        btsai.setText("SAI");
        btsai.setBorder(null);
        btsai.setBorderPainted(false);
        btsai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaiActionPerformed(evt);
            }
        });

        btdokho1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btdokho1.setText("1-100");
        btdokho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdokho1ActionPerformed(evt);
            }
        });

        btdokho2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btdokho2.setText("101-500");
        btdokho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdokho2ActionPerformed(evt);
            }
        });

        btdokho3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btdokho3.setText("501-1000");
        btdokho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdokho3ActionPerformed(evt);
            }
        });

        btdung.setBackground(new java.awt.Color(204, 255, 255));
        btdung.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        btdung.setForeground(new java.awt.Color(255, 0, 0));
        btdung.setText("ĐÚNG");
        btdung.setBorder(null);
        btdung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdungActionPerformed(evt);
            }
        });

        btcuu.setBackground(new java.awt.Color(204, 204, 204));
        btcuu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btcuu.setText("Cứu");
        btcuu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btcuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcuuActionPerformed(evt);
            }
        });

        bthoisinh.setBackground(new java.awt.Color(204, 204, 204));
        bthoisinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bthoisinh.setText("Hồi sinh");
        bthoisinh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bthoisinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthoisinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbcauhoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btdung)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btsai, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btcuu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bthoisinh))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(lbasd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbdiem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbkyluc)))
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btchoi, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btdokho1)
                                .addGap(18, 18, 18)
                                .addComponent(btdokho2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbdokho)
                                .addGap(17, 17, 17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btdokho3)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btdokho1, btdokho2, btdokho3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btdung, btsai});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btcuu, bthoisinh});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbasd)
                    .addComponent(lbdiem)
                    .addComponent(jLabel2)
                    .addComponent(lbkyluc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bthoisinh)
                    .addComponent(btcuu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbcauhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsai, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btdung, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btchoi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbdokho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btdokho1)
                    .addComponent(btdokho2)
                    .addComponent(btdokho3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btdokho1, btdokho2, btdokho3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btcuu, bthoisinh});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btdung, btsai});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void btthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btthoatActionPerformed

    private void btchoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchoiActionPerformed
        ketthuc = false;
        diem = -1;
        moctg = 100;
        tg = moctg; //100
        time = new Timer(100, new loadtime());
        time.start();
        load();
        btdokho1.setEnabled(false);
        btdokho2.setEnabled(false);
        btdokho3.setEnabled(false);
        lbdokho.setEnabled(false);
        btchoi.setEnabled(false);
        btcuu.setEnabled(false);
        bthoisinh.setEnabled(false);
        btdung.setEnabled(true);
        btsai.setEnabled(true);
    }//GEN-LAST:event_btchoiActionPerformed

    private void btsaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaiActionPerformed
        if(ketthuc == false)
        {
            if(diem % 10 == 0 && diem != 0) //Mỗi 10 điểm thì được hồi sinh
            {
                bthoisinh.setEnabled(true);
            }
            if(a + b != kq && a - b != kq)
            {
                load();
                if(diem == 5 || diem == 10 || diem == 15 || diem == 20) //Mỗi 5 câu thời gian sẽ giảm 15%
                {
                    moctg -= 15;
                    btcuu.setEnabled(true);
                }
                tg = moctg;
                time.start();
            }else //Khi trả lời sai đáp án
            {
                ketthuc = true;
                lbcauhoi.setText("Sai rồi");
                btchoi.setText("CHƠI LẠI");
                btchoi.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btsaiActionPerformed

    private void btdungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdungActionPerformed
        if(ketthuc == false)
        {
            if(diem % 10 == 0 && diem != 0) //Mỗi 10 điểm thì được hồi sinh
            {
                bthoisinh.setEnabled(true);
            }
            if(a + b == kq || a - b == kq)
            {
                load();
                if(diem == 5 || diem == 10 || diem == 15 || diem == 20) //Mỗi 5 câu thời gian sẽ giảm 15%
                {
                    moctg -= 15;
                    btcuu.setEnabled(true);
                }
                tg = moctg;
                time.start();
            }else //Khi trả lời sai đáp án
            {
                ketthuc = true;
                lbcauhoi.setText("Sai rồi");
                btchoi.setText("CHƠI LẠI");
                btchoi.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btdungActionPerformed

    private void btdokho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdokho1ActionPerformed
        dokho = 99;
    }//GEN-LAST:event_btdokho1ActionPerformed

    private void btdokho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdokho2ActionPerformed
        dokho = 499;
    }//GEN-LAST:event_btdokho2ActionPerformed

    private void btdokho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdokho3ActionPerformed
        dokho = 999;
    }//GEN-LAST:event_btdokho3ActionPerformed

    private void btcuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcuuActionPerformed
        if(diem == 0) //Khi mới vô người chơi chưa nhấn "BẮT ĐẦU" đã nhấn cứu thì sẽ Enabled các nút và người chơi cần nhấn "BẮT ĐẦU"
        {
            btcuu.setEnabled(false);
            bthoisinh.setEnabled(false);
            btdung.setEnabled(false);
            btsai.setEnabled(false);
        }
        btcuu.setEnabled(false); // Khi dùng "CỨU" thì sẽ Enabled lại nút "CỨU"
        diem--;
        load();
        tg = moctg;
        time.start();
    }//GEN-LAST:event_btcuuActionPerformed

    private void bthoisinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthoisinhActionPerformed
        if(diem == 0) //Khi mới vô người chơi chưa nhấn "BẮT ĐẦU" đã nhấn hồi sinh thì sẽ Enabled các nút và người chơi cần nhấn "BẮT ĐẦU"
        {
            btcuu.setEnabled(false);
            bthoisinh.setEnabled(false);
            btdung.setEnabled(false);
            btsai.setEnabled(false);
        }
        bthoisinh.setEnabled(false); // Khi dùng "HỒI SINH" thì sẽ Enabled lại nút "HỒI SINH"
        diem--;
        load();
        tg = moctg;
        time.start();
        btdung.setEnabled(true);
        btsai.setEnabled(true);
    }//GEN-LAST:event_bthoisinhActionPerformed
    
    public class loadtime implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            if(tg > 0)
            {
                tg--;
                Progress.setValue(tg);
            }else
            {
                lbcauhoi.setText("Kết thúc - Điểm là: "+ diem);
                btcuu.setEnabled(false);
                btsai.setEnabled(false);
                btdung.setEnabled(false);
                //Khi hết thời gian các núi "CỨU ĐÚNG SAI" sẽ bị Enabled riêng "HỒI SINH VẪN CÓ THỂ DÙNG"
            }
        }  
    }
    
    public void load(){
        diem++;
        lbdiem.setText(diem+"");
        btchoi.setText("CHƠI LẠI");
        Random r = new Random();
        a = r.nextInt(dokho) + 1;
        b = r.nextInt(dokho) + 1;
        kt = r.nextInt(11);
        if(kt == 0 || kt == 1 || kt == 2) //0-1-2 25% đúng +
        {
            kq = a + b;
            lbcauhoi.setText(a+" + "+b+" = "+kq);
        }
        else if(kt == 3 || kt == 4 || kt == 5) //3-4-5 25% đúng -
        {
            kq = a - b;
            lbcauhoi.setText(a+" - "+b+" = "+kq);
        }else if(kt == 6 || kt == 7 || kt == 8) //6-7-8 25% sai -
        {
            kq = r.nextInt(dokho*2);
            lbcauhoi.setText(a+" - "+b+" = "+kq);
        }
        else //9-10-11 25% sai +
        {
            kq = r.nextInt(dokho*2);
            lbcauhoi.setText(a+" + "+b+" = "+kq);
        }
        
        if(max < diem)
        {
            max = diem;
            lbkyluc.setText(diem + "");
        }
    }    
       
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progress;
    private javax.swing.JButton btchoi;
    private javax.swing.JButton btcuu;
    private javax.swing.JButton btdokho1;
    private javax.swing.JButton btdokho2;
    private javax.swing.JButton btdokho3;
    private javax.swing.JButton btdung;
    private javax.swing.JButton bthoisinh;
    private javax.swing.JButton btsai;
    private javax.swing.JButton btthoat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbasd;
    private javax.swing.JLabel lbcauhoi;
    private javax.swing.JLabel lbdiem;
    private javax.swing.JLabel lbdokho;
    private javax.swing.JLabel lbkyluc;
    // End of variables declaration//GEN-END:variables
}
